-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Enum.LogoutMode exposing (..)

import Json.Decode as Decode exposing (Decoder)


type LogoutMode
    = ThisSession
    | AllSessions


list : List LogoutMode
list =
    [ ThisSession, AllSessions ]


decoder : Decoder LogoutMode
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ThisSession" ->
                        Decode.succeed ThisSession

                    "AllSessions" ->
                        Decode.succeed AllSessions

                    _ ->
                        Decode.fail ("Invalid LogoutMode type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : LogoutMode -> String
toString enum____ =
    case enum____ of
        ThisSession ->
            "ThisSession"

        AllSessions ->
            "AllSessions"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe LogoutMode
fromString enumString____ =
    case enumString____ of
        "ThisSession" ->
            Just ThisSession

        "AllSessions" ->
            Just AllSessions

        _ ->
            Nothing
