apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    component: frontend