apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}
    component: postgres
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Release.Name }}
    component: postgres