-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Accessors exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


isAllowList : SelectionSet Bool LondoGQL.Object.Accessors
isAllowList =
    Object.selectionForField "Bool" "isAllowList" [] Decode.bool


userIds :
    SelectionSet decodesTo LondoGQL.Object.NonEmptyList
    -> SelectionSet (Maybe decodesTo) LondoGQL.Object.Accessors
userIds object____ =
    Object.selectionForCompositeField "userIds" [] object____ (Basics.identity >> Decode.nullable)
