-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.DashboardStatistics exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


reached :
    SelectionSet decodesTo LondoGQL.Object.WithSimulationNatural
    -> SelectionSet decodesTo LondoGQL.Object.DashboardStatistics
reached object____ =
    Object.selectionForCompositeField "reached" [] object____ Basics.identity


reachable :
    SelectionSet decodesTo LondoGQL.Object.WithoutSimulation
    -> SelectionSet decodesTo LondoGQL.Object.DashboardStatistics
reachable object____ =
    Object.selectionForCompositeField "reachable" [] object____ Basics.identity


absoluteMeans :
    SelectionSet decodesTo LondoGQL.Object.WithSimulationRational
    -> SelectionSet decodesTo LondoGQL.Object.DashboardStatistics
absoluteMeans object____ =
    Object.selectionForCompositeField "absoluteMeans" [] object____ Basics.identity


relativeMeans :
    SelectionSet decodesTo LondoGQL.Object.WithSimulationRational
    -> SelectionSet decodesTo LondoGQL.Object.DashboardStatistics
relativeMeans object____ =
    Object.selectionForCompositeField "relativeMeans" [] object____ Basics.identity
