-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Dashboard exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.Enum.Visibility
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


id :
    SelectionSet decodesTo LondoGQL.Object.DashboardId
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
id object____ =
    Object.selectionForCompositeField "id" [] object____ Basics.identity


header : SelectionSet String LondoGQL.Object.Dashboard
header =
    Object.selectionForField "String" "header" [] Decode.string


description : SelectionSet (Maybe String) LondoGQL.Object.Dashboard
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


visibility : SelectionSet LondoGQL.Enum.Visibility.Visibility LondoGQL.Object.Dashboard
visibility =
    Object.selectionForField "Enum.Visibility.Visibility" "visibility" [] LondoGQL.Enum.Visibility.decoder
