-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Dashboard exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


id :
    SelectionSet decodesTo LondoGQL.Object.DashboardId
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
id object____ =
    Object.selectionForCompositeField "id" [] object____ Basics.identity


projects :
    SelectionSet decodesTo LondoGQL.Object.WeightedProject
    -> SelectionSet (List decodesTo) LondoGQL.Object.Dashboard
projects object____ =
    Object.selectionForCompositeField "projects" [] object____ (Basics.identity >> Decode.list)


header : SelectionSet String LondoGQL.Object.Dashboard
header =
    Object.selectionForField "String" "header" [] Decode.string


description : SelectionSet (Maybe String) LondoGQL.Object.Dashboard
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


userId :
    SelectionSet decodesTo LondoGQL.Object.UserId
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
userId object____ =
    Object.selectionForCompositeField "userId" [] object____ Basics.identity


readAccessors :
    SelectionSet decodesTo LondoGQL.Object.Accessors
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
readAccessors object____ =
    Object.selectionForCompositeField "readAccessors" [] object____ Basics.identity


writeAccessors :
    SelectionSet decodesTo LondoGQL.Object.Accessors
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
writeAccessors object____ =
    Object.selectionForCompositeField "writeAccessors" [] object____ Basics.identity
