-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Plain exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.Enum.TaskKind
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


id :
    SelectionSet decodesTo LondoGQL.Object.TaskId
    -> SelectionSet decodesTo LondoGQL.Object.Plain
id object____ =
    Object.selectionForCompositeField "id" [] object____ Basics.identity


name : SelectionSet String LondoGQL.Object.Plain
name =
    Object.selectionForField "String" "name" [] Decode.string


taskKind : SelectionSet LondoGQL.Enum.TaskKind.TaskKind LondoGQL.Object.Plain
taskKind =
    Object.selectionForField "Enum.TaskKind.TaskKind" "taskKind" [] LondoGQL.Enum.TaskKind.decoder


unit : SelectionSet (Maybe String) LondoGQL.Object.Plain
unit =
    Object.selectionForField "(Maybe String)" "unit" [] (Decode.string |> Decode.nullable)


progress :
    SelectionSet decodesTo LondoGQL.Object.Progress
    -> SelectionSet decodesTo LondoGQL.Object.Plain
progress object____ =
    Object.selectionForCompositeField "progress" [] object____ Basics.identity


weight : SelectionSet LondoGQL.ScalarCodecs.Positive LondoGQL.Object.Plain
weight =
    Object.selectionForField "ScalarCodecs.Positive" "weight" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecPositive |> .decoder)
