-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Progress exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


reached :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.Progress
reached object____ =
    Object.selectionForCompositeField "reached" [] object____ Basics.identity


reachable :
    SelectionSet decodesTo LondoGQL.Object.Positive
    -> SelectionSet decodesTo LondoGQL.Object.Progress
reachable object____ =
    Object.selectionForCompositeField "reachable" [] object____ Basics.identity
