-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.Rational exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


numerator : SelectionSet LondoGQL.ScalarCodecs.BigInt LondoGQL.Object.Rational
numerator =
    Object.selectionForField "ScalarCodecs.BigInt" "numerator" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecBigInt |> .decoder)


denominator :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.Rational
denominator object____ =
    Object.selectionForCompositeField "denominator" [] object____ Basics.identity
