-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.ResolvedTask exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


task :
    SelectionSet decodesTo LondoGQL.Object.Task
    -> SelectionSet decodesTo LondoGQL.Object.ResolvedTask
task object____ =
    Object.selectionForCompositeField "task" [] object____ Basics.identity


simulation :
    SelectionSet decodesTo LondoGQL.Object.Simulation
    -> SelectionSet (Maybe decodesTo) LondoGQL.Object.ResolvedTask
simulation object____ =
    Object.selectionForCompositeField "simulation" [] object____ (Basics.identity >> Decode.nullable)
