-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.ResolvedProjectReference exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


id :
    SelectionSet decodesTo LondoGQL.Object.TaskId
    -> SelectionSet decodesTo LondoGQL.Object.ResolvedProjectReference
id object____ =
    Object.selectionForCompositeField "id" [] object____ Basics.identity


project :
    SelectionSet decodesTo LondoGQL.Object.ResolvedProject
    -> SelectionSet decodesTo LondoGQL.Object.ResolvedProjectReference
project object____ =
    Object.selectionForCompositeField "project" [] object____ Basics.identity


weight :
    SelectionSet decodesTo LondoGQL.Object.Positive
    -> SelectionSet decodesTo LondoGQL.Object.ResolvedProjectReference
weight object____ =
    Object.selectionForCompositeField "weight" [] object____ Basics.identity
