-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


id :
    SelectionSet decodesTo LondoGQL.Object.UserId
    -> SelectionSet decodesTo LondoGQL.Object.User
id object____ =
    Object.selectionForCompositeField "id" [] object____ Basics.identity


nickname : SelectionSet String LondoGQL.Object.User
nickname =
    Object.selectionForField "String" "nickname" [] Decode.string


email : SelectionSet String LondoGQL.Object.User
email =
    Object.selectionForField "String" "email" [] Decode.string


settings :
    SelectionSet decodesTo LondoGQL.Object.UserSettings
    -> SelectionSet decodesTo LondoGQL.Object.User
settings object____ =
    Object.selectionForCompositeField "settings" [] object____ Basics.identity


details :
    SelectionSet decodesTo LondoGQL.Object.UserDetails
    -> SelectionSet decodesTo LondoGQL.Object.User
details object____ =
    Object.selectionForCompositeField "details" [] object____ Basics.identity
