-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.WithSimulationNatural exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


total :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.WithSimulationNatural
total object____ =
    Object.selectionForCompositeField "total" [] object____ Basics.identity


counted :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.WithSimulationNatural
counted object____ =
    Object.selectionForCompositeField "counted" [] object____ Basics.identity


simulatedTotal :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.WithSimulationNatural
simulatedTotal object____ =
    Object.selectionForCompositeField "simulatedTotal" [] object____ Basics.identity


simulatedCounted :
    SelectionSet decodesTo LondoGQL.Object.Natural
    -> SelectionSet decodesTo LondoGQL.Object.WithSimulationNatural
simulatedCounted object____ =
    Object.selectionForCompositeField "simulatedCounted" [] object____ Basics.identity
