-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object.WithSimulationBigDecimal exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


total : SelectionSet LondoGQL.ScalarCodecs.BigDecimal LondoGQL.Object.WithSimulationBigDecimal
total =
    Object.selectionForField "ScalarCodecs.BigDecimal" "total" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


counted : SelectionSet LondoGQL.ScalarCodecs.BigDecimal LondoGQL.Object.WithSimulationBigDecimal
counted =
    Object.selectionForField "ScalarCodecs.BigDecimal" "counted" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


simulatedTotal : SelectionSet LondoGQL.ScalarCodecs.BigDecimal LondoGQL.Object.WithSimulationBigDecimal
simulatedTotal =
    Object.selectionForField "ScalarCodecs.BigDecimal" "simulatedTotal" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


simulatedCounted : SelectionSet LondoGQL.ScalarCodecs.BigDecimal LondoGQL.Object.WithSimulationBigDecimal
simulatedCounted =
    Object.selectionForField "ScalarCodecs.BigDecimal" "simulatedCounted" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
