name: Auto-merge Pull Request

description: Approves and merges a pull request using the GH_TOKEN environment variable

runs:
  using: composite
  steps:
    - name: Approve Pull Request
      shell: bash
      run: gh pr review --approve ${{ github.event.pull_request.html_url }}
    - name: Merge Pull Request
      shell: bash
      run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}