-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import LondoGQL.InputObject
import LondoGQL.Interface
import LondoGQL.Object
import LondoGQL.Scalar
import LondoGQL.ScalarCodecs
import LondoGQL.Union


type alias LoginRequiredArguments =
    { input : LondoGQL.InputObject.LoginInput }


login :
    LoginRequiredArguments
    -> SelectionSet String RootMutation
login requiredArgs____ =
    Object.selectionForField "String" "login" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeLoginInput ] Decode.string


type alias LogoutRequiredArguments =
    { input : LondoGQL.InputObject.LogoutInput }


logout :
    LogoutRequiredArguments
    -> SelectionSet Bool RootMutation
logout requiredArgs____ =
    Object.selectionForField "Bool" "logout" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeLogoutInput ] Decode.bool


type alias UpdateUserRequiredArguments =
    { input : LondoGQL.InputObject.UpdateUserInput }


updateUser :
    UpdateUserRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.User
    -> SelectionSet decodesTo RootMutation
updateUser requiredArgs____ object____ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdateUserInput ] object____ Basics.identity


type alias UpdatePasswordRequiredArguments =
    { input : LondoGQL.InputObject.UpdatePasswordInput }


updatePassword :
    UpdatePasswordRequiredArguments
    -> SelectionSet Bool RootMutation
updatePassword requiredArgs____ =
    Object.selectionForField "Bool" "updatePassword" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdatePasswordInput ] Decode.bool


type alias RequestRegistrationRequiredArguments =
    { input : LondoGQL.InputObject.RequestRegistrationInput }


requestRegistration :
    RequestRegistrationRequiredArguments
    -> SelectionSet LondoGQL.ScalarCodecs.Unit RootMutation
requestRegistration requiredArgs____ =
    Object.selectionForField "ScalarCodecs.Unit" "requestRegistration" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeRequestRegistrationInput ] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecUnit |> .decoder)


type alias ConfirmRegistrationRequiredArguments =
    { input : LondoGQL.InputObject.ConfirmRegistrationInput }


confirmRegistration :
    ConfirmRegistrationRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.User
    -> SelectionSet decodesTo RootMutation
confirmRegistration requiredArgs____ object____ =
    Object.selectionForCompositeField "confirmRegistration" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeConfirmRegistrationInput ] object____ Basics.identity


type alias RequestRecoveryRequiredArguments =
    { input : LondoGQL.InputObject.RequestRecoveryInput }


requestRecovery :
    RequestRecoveryRequiredArguments
    -> SelectionSet LondoGQL.ScalarCodecs.Unit RootMutation
requestRecovery requiredArgs____ =
    Object.selectionForField "ScalarCodecs.Unit" "requestRecovery" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeRequestRecoveryInput ] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecUnit |> .decoder)


type alias ConfirmRecoveryRequiredArguments =
    { input : LondoGQL.InputObject.ConfirmRecoveryInput }


confirmRecovery :
    ConfirmRecoveryRequiredArguments
    -> SelectionSet Bool RootMutation
confirmRecovery requiredArgs____ =
    Object.selectionForField "Bool" "confirmRecovery" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeConfirmRecoveryInput ] Decode.bool


requestDeletion : SelectionSet LondoGQL.ScalarCodecs.Unit RootMutation
requestDeletion =
    Object.selectionForField "ScalarCodecs.Unit" "requestDeletion" [] (LondoGQL.ScalarCodecs.codecs |> LondoGQL.Scalar.unwrapCodecs |> .codecUnit |> .decoder)


type alias ConfirmDeletionRequiredArguments =
    { input : LondoGQL.InputObject.ConfirmDeletionInput }


confirmDeletion :
    ConfirmDeletionRequiredArguments
    -> SelectionSet Bool RootMutation
confirmDeletion requiredArgs____ =
    Object.selectionForField "Bool" "confirmDeletion" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeConfirmDeletionInput ] Decode.bool


type alias CreateProjectRequiredArguments =
    { input : LondoGQL.InputObject.CreateProjectInput }


createProject :
    CreateProjectRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Project
    -> SelectionSet decodesTo RootMutation
createProject requiredArgs____ object____ =
    Object.selectionForCompositeField "createProject" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeCreateProjectInput ] object____ Basics.identity


type alias UpdateProjectRequiredArguments =
    { input : LondoGQL.InputObject.UpdateProjectInput }


updateProject :
    UpdateProjectRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Project
    -> SelectionSet decodesTo RootMutation
updateProject requiredArgs____ object____ =
    Object.selectionForCompositeField "updateProject" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdateProjectInput ] object____ Basics.identity


type alias DeleteProjectRequiredArguments =
    { input : LondoGQL.InputObject.DeleteProjectInput }


deleteProject :
    DeleteProjectRequiredArguments
    -> SelectionSet Bool RootMutation
deleteProject requiredArgs____ =
    Object.selectionForField "Bool" "deleteProject" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeDeleteProjectInput ] Decode.bool


type alias CreateTaskRequiredArguments =
    { input : LondoGQL.InputObject.CreateTaskInput }


createTask :
    CreateTaskRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Task
    -> SelectionSet decodesTo RootMutation
createTask requiredArgs____ object____ =
    Object.selectionForCompositeField "createTask" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeCreateTaskInput ] object____ Basics.identity


type alias UpdateTaskRequiredArguments =
    { input : LondoGQL.InputObject.UpdateTaskInput }


updateTask :
    UpdateTaskRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Task
    -> SelectionSet decodesTo RootMutation
updateTask requiredArgs____ object____ =
    Object.selectionForCompositeField "updateTask" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdateTaskInput ] object____ Basics.identity


type alias DeleteTaskRequiredArguments =
    { input : LondoGQL.InputObject.DeleteTaskInput }


deleteTask :
    DeleteTaskRequiredArguments
    -> SelectionSet Bool RootMutation
deleteTask requiredArgs____ =
    Object.selectionForField "Bool" "deleteTask" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeDeleteTaskInput ] Decode.bool


type alias CreateDashboardRequiredArguments =
    { input : LondoGQL.InputObject.CreateDashboardInput }


createDashboard :
    CreateDashboardRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
    -> SelectionSet decodesTo RootMutation
createDashboard requiredArgs____ object____ =
    Object.selectionForCompositeField "createDashboard" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeCreateDashboardInput ] object____ Basics.identity


type alias UpdateDashboardRequiredArguments =
    { input : LondoGQL.InputObject.UpdateDashboardInput }


updateDashboard :
    UpdateDashboardRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Dashboard
    -> SelectionSet decodesTo RootMutation
updateDashboard requiredArgs____ object____ =
    Object.selectionForCompositeField "updateDashboard" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdateDashboardInput ] object____ Basics.identity


type alias DeleteDashboardRequiredArguments =
    { input : LondoGQL.InputObject.DeleteDashboardInput }


deleteDashboard :
    DeleteDashboardRequiredArguments
    -> SelectionSet Bool RootMutation
deleteDashboard requiredArgs____ =
    Object.selectionForField "Bool" "deleteDashboard" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeDeleteDashboardInput ] Decode.bool


type alias CreateDashboardEntryRequiredArguments =
    { input : LondoGQL.InputObject.CreateDashboardEntryInput }


createDashboardEntry :
    CreateDashboardEntryRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.DashboardEntry
    -> SelectionSet decodesTo RootMutation
createDashboardEntry requiredArgs____ object____ =
    Object.selectionForCompositeField "createDashboardEntry" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeCreateDashboardEntryInput ] object____ Basics.identity


type alias DeleteDashboardEntryRequiredArguments =
    { input : LondoGQL.InputObject.DeleteDashboardEntryInput }


deleteDashboardEntry :
    DeleteDashboardEntryRequiredArguments
    -> SelectionSet Bool RootMutation
deleteDashboardEntry requiredArgs____ =
    Object.selectionForField "Bool" "deleteDashboardEntry" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeDeleteDashboardEntryInput ] Decode.bool


type alias CreateSimulationRequiredArguments =
    { input : LondoGQL.InputObject.CreateSimulationInput }


createSimulation :
    CreateSimulationRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.Simulation
    -> SelectionSet decodesTo RootMutation
createSimulation requiredArgs____ object____ =
    Object.selectionForCompositeField "createSimulation" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeCreateSimulationInput ] object____ Basics.identity


type alias UpdateTaskWithSimulationRequiredArguments =
    { input : LondoGQL.InputObject.UpdateTaskWithSimulationInput }


updateTaskWithSimulation :
    UpdateTaskWithSimulationRequiredArguments
    -> SelectionSet decodesTo LondoGQL.Object.ResolvedTask
    -> SelectionSet decodesTo RootMutation
updateTaskWithSimulation requiredArgs____ object____ =
    Object.selectionForCompositeField "updateTaskWithSimulation" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeUpdateTaskWithSimulationInput ] object____ Basics.identity


type alias DeleteSimulationRequiredArguments =
    { input : LondoGQL.InputObject.DeleteSimulationInput }


deleteSimulation :
    DeleteSimulationRequiredArguments
    -> SelectionSet Bool RootMutation
deleteSimulation requiredArgs____ =
    Object.selectionForField "Bool" "deleteSimulation" [ Argument.required "input" requiredArgs____.input LondoGQL.InputObject.encodeDeleteSimulationInput ] Decode.bool
