-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object exposing (..)


type After
    = After


type Dashboard
    = Dashboard


type DashboardAnalysis
    = DashboardAnalysis


type DashboardEntry
    = DashboardEntry


type DashboardId
    = DashboardId


type DashboardStatistics
    = DashboardStatistics


type FindUserResult
    = FindUserResult


type IncompleteTaskStatistics
    = IncompleteTaskStatistics


type Natural
    = Natural


type Positive
    = Positive


type Progress
    = Progress


type Project
    = Project


type ProjectAnalysis
    = ProjectAnalysis


type ProjectId
    = ProjectId


type ResolvedDashboard
    = ResolvedDashboard


type ResolvedProject
    = ResolvedProject


type Simulation
    = Simulation


type Task
    = Task


type TaskAnalysis
    = TaskAnalysis


type TaskId
    = TaskId


type User
    = User


type UserId
    = UserId


type WithSimulationBigDecimal
    = WithSimulationBigDecimal


type WithSimulationNatural
    = WithSimulationNatural


type WithoutSimulation
    = WithoutSimulation
