-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object exposing (..)


type Dashboard
    = Dashboard


type DashboardEntry
    = DashboardEntry


type DashboardId
    = DashboardId


type FindUserResult
    = FindUserResult


type Natural
    = Natural


type Positive
    = Positive


type Progress
    = Progress


type Project
    = Project


type ProjectId
    = ProjectId


type ResolvedDashboard
    = ResolvedDashboard


type ResolvedProject
    = ResolvedProject


type Task
    = Task


type TaskId
    = TaskId


type User
    = User


type UserId
    = UserId
