-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.Object exposing (..)


type Accessors
    = Accessors


type Dashboard
    = Dashboard


type DashboardId
    = DashboardId


type NonEmptyList
    = NonEmptyList


type Plain
    = Plain


type Progress
    = Progress


type Project
    = Project


type ProjectId
    = ProjectId


type ProjectReference
    = ProjectReference


type ResolvedPlain
    = ResolvedPlain


type ResolvedProject
    = ResolvedProject


type ResolvedProjectReference
    = ResolvedProjectReference


type TaskId
    = TaskId


type User
    = User


type UserDetails
    = UserDetails


type UserId
    = UserId


type UserSettings
    = UserSettings


type WeightedProject
    = WeightedProject
