-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import LondoGQL.Scalar exposing (defaultCodecs)


type alias Unit =
    LondoGQL.Scalar.Unit


type alias Uuid =
    LondoGQL.Scalar.Uuid


codecs : LondoGQL.Scalar.Codecs Unit Uuid
codecs =
    LondoGQL.Scalar.defineCodecs
        { codecUnit = defaultCodecs.codecUnit
        , codecUuid = defaultCodecs.codecUuid
        }
