-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LondoGQL.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import LondoGQL.Scalar exposing (defaultCodecs)


type alias Natural =
    LondoGQL.Scalar.Natural


type alias Positive =
    LondoGQL.Scalar.Positive


type alias Unit =
    LondoGQL.Scalar.Unit


type alias Uuid =
    LondoGQL.Scalar.Uuid


codecs : LondoGQL.Scalar.Codecs Natural Positive Unit Uuid
codecs =
    LondoGQL.Scalar.defineCodecs
        { codecNatural = defaultCodecs.codecNatural
        , codecPositive = defaultCodecs.codecPositive
        , codecUnit = defaultCodecs.codecUnit
        , codecUuid = defaultCodecs.codecUuid
        }
