name: Run Scala tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Prepare environment, and run Scala tests
    runs-on: ubuntu-latest
    permissions: {}
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: londo_test
          POSTGRES_PASSWORD: 5WuVjFBUWYWasGBLpw7MtNvLL87Mn7RgH09wlsBH
          POSTGRES_PORT: 5432
          POSTGRES_USER: londo_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up JDK 25
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Set up SBT
        uses: sbt/setup-sbt@f6db8ab474efba716fc7f04441ab33714e4825af # v1.5.4
      - name: Run tests
        run: sbt test