name: Auto-merge Dependabot Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0

      - name: Determine auto-merge eligibility
        id: check-eligibility
        run: |
          echo "eligible=$(if [[ '${{ steps.dependabot-metadata.outputs.update-type }}' != 'version-update:semver-major' ]]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      - name: Check out
        if: steps.check-eligibility.outputs.eligible == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Auto-merge
        if: steps.check-eligibility.outputs.eligible == 'true'
        uses: ./.github/actions/auto-merge