name: Build and publish Docker frontend image

on:
  push:
    branches:
      - "main"
    paths:
      - frontend/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install create-elm-app
        run: npm install create-elm-app -g
      - name: Build Elm app
#       The secret handling is questionable,
#       because the variables are readable from the result.
        run: |
          cd frontend
          rm .env
          export ELM_APP_BACKEND_URL=${{ secrets.ELM_APP_BACKEND_URL }}
          export ELM_APP_MAIN_PAGE_URL=${{ secrets.ELM_APP_MAIN_PAGE_URL }}
          elm-app build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: nikitadanilenko/londo-frontend
          tags: |
            type=sha
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
