name: Run Scala tests

on:
  pull_request:
    branches:
      - "main"
    paths:
      - app/**
      - test/**
      - conf/**
      - build.sbt

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: londo_test
          POSTGRES_PASSWORD: 5WuVjFBUWYWasGBLpw7MtNvLL87Mn7RgH09wlsBH
          POSTGRES_PORT: 5432
          POSTGRES_USER: londo_test
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
