name: Build and publish Docker backend image

on:
  push:
    branches:
      - "main"
    paths:
      - app/**
      - test/**
      - conf/**
      - build.sbt
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      # Technically, we could use 'sbt "Docker / publish"',
      # but one would need to handle the credentials elsewhere.
      - name: Prepare Docker image
        run: sbt "Docker / stage"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: nikitadanilenko/londo
          tags: |
            type=sha
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: target/docker/stage
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
