name: Verify pull request

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      back-end-paths-changed: ${{ steps.back-end.outputs.back-end-src }}
      front-end-paths-changed: ${{ steps.front-end.outputs.front-end-src }}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: back-end
        with:
          filters: |
            back-end-src:
              - 'app/**'
              - 'test/**'
              - 'conf/**'
              - 'build.sbt'
              - 'project/**'
              - '.scalafmt.conf'
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: front-end
        with:
          filters: |
            front-end-src:
              - 'frontend/**'

  back-end-test:
    needs: changes
    if: ${{ needs.changes.outputs.back-end-paths-changed == 'true' }}
    uses: ./.github/workflows/_scala-tests.yml

  front-end-test:
    needs: changes
    if: ${{ needs.changes.outputs.front-end-paths-changed == 'true' }}
    uses: ./.github/workflows/_elm-tests.yml

  combine-tests:
    needs:
      - back-end-test
      - front-end-test
    runs-on: ubuntu-latest
    if: always() && (needs.back-end-test.result == 'success' || needs.back-end-test.result == 'skipped') && (needs.front-end-test.result == 'success' || needs.front-end-test.result == 'skipped')
    steps:
      - name: Finish test
        run: echo "All tests passed"